###post 
POST http://localhost:1986/books/upload
Content-Type: application/json

{
  "userId": "67f13f158b45e96b2ba9412c",
  "category": "Computer Science 3",
  "title": "Introduction to Algorithms 3",
  "author": "Cormen",
  "tags": ["algorithms", "data structures", "cs"]
}

###take a book 
PATCH http://localhost:1986/books/take/67f13f2b8b45e96b2ba94132
Content-Type: application/json

{
  "userId": "67f13f158b45e96b2ba9412c"
}

### return a book
PATCH http://localhost:1986/books/return/67f13f2b8b45e96b2ba94132
Content-Type: application/json

{
  "userId": "67f13f158b45e96b2ba9412c"
}

###get all books
GET http://localhost:1986/books

###get book by id
GET http://localhost:1986/books/67f13f2b8b45e96b2ba94132

