###post
post http://localhost:1986/studentUser/createUser
Content-Type: application/json

{
  "userName":"userName 123",
  "firstName":"user",
  "lastName":"user 2",
  "email":"user123@mail",
  "role":"faculty",
  "profileImageUrl":"user123 image",
  "isOurClg":true
}
###get
get http://localhost:1986/studentUser/getUsers
###get by id
get http://localhost:1986/studentUser/getUser/67f12a3778e9dfe85271f188
###update by id
put http://localhost:1986/studentUser/updateUser/67f12a3778e9dfe85271f188
Content-Type: application/json

{
    "firstName":"user 21  firstName",
    "lastName":"user 21 LastName"
}
###block a user
PATCH http://localhost:1986/studentUser/blockUser/67f12a3778e9dfe85271f188



